#!/bin/python3

import sys

n = int(input().strip())
a = list(map(int, input().strip().split(' ')))
# Write Your Code Here
swaps=0
for i in range(n-1):
    for j in range(i+1,n):
        if a[i]>a[j]:
            temp=a[i]
            a[i]=a[j]
            a[j]=temp
            swaps+=1

print("Array is sorted in",swaps,"swaps.")
print("First Element:",a[0])
print("Last Element:",a[n-1])
