#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())

binString=""
temp=n
while n>0:
    binString+=str(n%2)
    n=n//2
binString = binString[::-1]

consecutive=1
maxCount=[]
count=0
for i in binString:
    if i=='1':
        count+=1
        maxCount.append(count)
    else:
        count=0
                
print(max(maxCount))
        


