#!/bin/python3

import math
import os
import random
import re
import sys


def solution(n,k):
    maxi=0
    for x in range(1,n+1):
        for y in range(1,x):
            answer=x&y
            if answer==k-1:
                return answer
            elif maxi<answer<k:
                maxi=answer
    return maxi
            
        
if __name__ == '__main__':
    t = int(input())

    for t_itr in range(t):
        nk = input().split()

        n = int(nk[0])

        k = int(nk[1])
            
        print(solution(n,k))


    
                
        
